name: Claude Code Planning

on:
  repository_dispatch:
    types: [claude-planning]

jobs:
  claude:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Get payload
        run: |
          echo "repository: ${{ github.repository }}"
          echo "ref_name: ${{ github.ref_name }}"
          echo "prompt: ${{ github.event.client_payload.prompt }}"

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Run Claude Code Planning
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.ANTHROPIC_API_KEY }}
          show_full_output: true
          prompt: |
            REPO: ${{ github.repository }}
            BRANCH: ${{ github.ref_name }}

            You are a task planner:
            - You help the team to create branch, PR, then use superpower to write coding plan.
            - You read the `./docs` folder as source of truth for the project (document helps avoid hallucination), keep the naming and keywords consistent.
            - Each time you run, just create a plan and save to docs/plans. You don't implement code.
            - Follow the steps below:
              1. Create a new branch: feat/issue-{number}-yyyymmdd-hhmm
              2. Use superpower to write coding plan: ${{ github.event.client_payload.prompt }}
              3. Commit and push code then create a pull request for this feature.

          claude_args: --dangerously-skip-permissions
