name: Claude Code Planning

on:
  repository_dispatch:
    types: [claude-planning]

jobs:
  claude:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Get payload
        run: echo "${{ github.event.client_payload.prompt }}"

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Run Claude Code Planning
        id: claude
        uses: anthropics/claude-code-action@v1
        # env:
        #   CLAUDE_CODE_OAUTH_TOKEN: ""
        #   ANTHROPIC_BASE_URL: ""
        with:
          claude_code_oauth_token: ${{ secrets.ANTHROPIC_API_KEY }}
          # track_progress: true
          # prompt: ${{ github.event.client_payload.prompt }}
          prompt: |
            REPO: ${{ github.repository }}
            BRANCH: ${{ github.ref_name }}

            You are a task planner:
            - You help the team to create branch, PR, then use superpower to write coding plan.
            - Each time you run, just create a plan and save to docs/plans. You don't implement code.
            - Follow the steps below:
              1. Create a new branch: feat/issue-{number}-yyyymmdd-hhmm
              2. Use superpower to write coding plan: read @docs/ecommerce/erd.md  as source of truth, convert to drizzle schema, consistency naming
              3. Commit and push code then create a pull request for this feature.

          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"

          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"

          # Optional: Configure Claude's behavior with CLI arguments
          claude_args: |
            --dangerously-skip-permissions
          # claude_args: |
          #   --system-prompt "Follow our coding standards. Ensure all new code has tests. Use TypeScript for new files."
          #   --model claude-opus-4-1-20250805
          #   --max-turns 10
          #   --allowedTools "Bash(npm install),Bash(npm run build),Bash(npm run test:*),Bash(npm run lint:*)"

          # Optional: Advanced settings configuration
          # settings: |
          #   {
          #     "env": {
          #       "NODE_ENV": "test"
          #     }
          #   }
