name: Deploy to Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          EMAIL: ${{ vars.SSL_EMAIL }}
          BRANCH: ${{ github.ref_name }}
        run: |
          echo "ðŸš€ Connecting to server $SERVER_IP"
          echo "ðŸš€ Deploying to domain $DOMAIN_NAME"
          echo "ðŸš€ User email $EMAIL"
          echo "ðŸš€ Branch $BRANCH"

          export BRANCH="$BRANCH"

          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-214-149-131.ap-southeast-1.compute.amazonaws.com << 'EOF'
            set -e

            echo "ðŸš€ Branch debug 2 $BRANCH"

            echo "ðŸ“¦ Downloading latest deployment script..."
            curl -o ~/deploy.sh https://raw.githubusercontent.com/quochuydev/x-app-v1/main/deploy.sh

            echo "ðŸ”§ Applying custom domain and email..."
            sed -i "s/app-v1.quochuy.dev/app-v1.quochuy.dev/g" ~/deploy.sh
            sed -i "s/admin@app-v1.quochuy.dev/quochuy.dev@gmail.com/g" ~/deploy.sh

            echo "âš™ï¸ Making deploy script executable..."
            chmod +x ~/deploy.sh

            echo "ðŸš€ Running deployment..."
            ./deploy.sh "$BRANCH"

            echo "âœ… Deployment complete"
          EOF
